In [42]:
import numpy as np

# Intro to Numpy

## Advantages to using numpy:
* computationally more efficient than using lists for large data sets
  * searching
  * arithmetic manipulation
* Because numpy is vectorized, iterating through all elements of a large data set are efficiently caluclated. No need for `for` loops. Makes code much more readable.

## Disadvantages to using numpy:
* data is kept in contiguous memory, so insertions, deletions or resizing can be inefficient


## Gotcha's and Notes
* __NOTE:__ Best to know the size and dimentions of the array prior to using numpy.ndarray types
* __NOTE:__ When printing array, commas are not present (see below)

In [ ]:
# Create an array
arr1 = np.arange(0,20,3)

When __displaying__ array: note that commas are present and the print out is prefixed with _array_

In [ ]:
# Display the array
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

When __printing__ the array, note that no commas are present and the output is displayed as type of list

In [ ]:
# print the array
print(arr1)

[ 0  3  6  9 12 15 18]


# Creating a Numpy Array objects



## Introduction

There are multiple ways to create a numpy array object

* NOTE: Numpy arrays must contain all the same data types all floats, all ints, etc

## Creating a numpy arrays from a list

In [51]:
# Define the list
arr_str = ["foo", "bar"]

# convert to a numpy array
np_array_str = np.array(arr_str)

# display the numpy array
np_array_str


array(['foo', 'bar'], dtype='<U3')

### What type are the arrays

In [52]:
print(type(arr_str), type(np_array_str))


<class 'list'> <class 'numpy.ndarray'>


### Creating multi-dimentional arrays from lists

To create a multi-dimentional array, we pass in a list of list into the `np.array` method.

In [53]:
# define a list of list that represents a 3x2 matrix
arr_2d = [
    [1,2],
    [3,4],
    [5,6]
]

# convert to a 2d numpy array
np_array_2d = np.array(arr_2d)

# Display the array
np_array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
# What is the size of the array?
print("Size of np_array_2d =", np_array_2d.size)

# What are the dimensions?
print(np_array_2d.shape)

Size of np_array_2d = 6
(3, 2)


## Numpy Methods for Creating Arrays

### np.arange

Like the `range` functions for lists, numpy has the `arange` method to generate an **array**

In [19]:
# creating a list with range
x = list(range(0, 10))

# display x
print(x)

# Create a numpy array using arange
npx = np.arange(0,10)

#display npx
npx

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

__NOTE:__ Both the `range` and `arange` methods are not inclusive of the _stop_ parameter.

Like `range` the `arange` method also has _step_ parameter, which specifies the step size between values.

In [21]:
# create a list of 0 through 9 at step size of 2
x = list(range(0, 10, 2))

# display x
print(x)

# Create a numpy array using arange with a step size of 0.5
npx = np.arange(0,10, 0.5)

#display npx
npx

[0, 2, 4, 6, 8]


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

__NOTE:__ that the step size for `range` can only be an integer, where as `arange` can accept floats as well.

### np.linspace()
`np.linspace()` creates an array of equally spaced (stepped) values.

In [25]:
# create an array of 50 elements from 0 to 10
npx = np.linspace(0,10)
print(npx)
print(npx.shape)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
(50,)


__NOTE:__ By default, the stop value is included in the output, this can be changed using the `endpoint` parameter

In [26]:
# Recreate the array without the stop value
npx = np.linspace(0,10, endpoint=False)
print(npx)
print(npx.shape)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(50,)


By default the formula used by the `linspace` method for calculating step size is:

__step = (stop - start)/(num - 1)__

In [28]:
start = 0
stop = 10
num = 50
step = (stop - start)/(num -1)
step


0.20408163265306123

When `endpoint` is set to false the step size is

__step = (stop - start)/num__

In [29]:
step = (stop - start)/num
step

0.2

__NOTE:__ Alternatively, if we wanted to keep the last value, and have a step of 0.2, we could just increase the number of steps by 1

In [43]:
# create an array of 51 elements from 0 to 10
npx = np.linspace(0,10, num=51)
print(npx)
print(npx.shape)

[ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10. ]
(51,)


In essence we are solving for `num` in the default formula above:

__num = ((stop - start)/step) + 1__

In [47]:
num = int(((stop - start)/step) + 1)
num

51

We can also create multi-dimentional arrays using `np.linspace()`

In [42]:
# Creating a 3d array where each element of the major axis is a 2x2 matrix that
# increments all elments by 2
x = np.linspace(
    start=(
        (0,10),
        (20,30)
      ),
    stop=(
        (10,20),
        (30,40)
      ),
    num=5,
    endpoint=False,
    dtype=int # keep as ints just to make it easier for visualize
)
print(x.shape)
print(x)

(5, 2, 2)
[[[ 0 10]
  [20 30]]

 [[ 2 12]
  [22 32]]

 [[ 4 14]
  [24 34]]

 [[ 6 16]
  [26 36]]

 [[ 8 18]
  [28 38]]]


### np.ones() & np.zeros() & np.eye()
Sometimes there are easier ways to create multi-dimentional arrays. the `np.ones()`, `np.zeros()` and `np.eye()` methods allow you to create arrays by passing in the desired shape.

#### np.ones()
`np.ones()` creates an array of ones of given shape.

In [41]:
desired_shape = (5,2,2)
x = np.ones(desired_shape, dtype=int)
print(x.shape)
print(x)

(5, 2, 2)
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


#### np.zeros()
`np.zeros()` creates an array of zeros of given shape

In [48]:
x = np.zeros(desired_shape, dtype=int)
print(x.shape)
print(x)

(5, 2, 2)
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


#### np.eye()
`np.eye()` generates the identity matrix for the given `m`.

In [50]:
x = np.eye(5,dtype=int)
x

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### NOTE on `dtype`
`dtype` is an optional parameter for many of the numpy methods. It allows you to specify the data type of all the elements contained within an array. More info here: https://numpy.org/doc/stable/user/basics.types.html

# Working With Numpy Arrays

## Reshaping Arrays

### `np.reshape()`
`np.reshape()` is a method that reshapes an array into a given shape. NOTE: that the product of all dimensions needs to be equal to the size of the input array for it to work.

In [56]:
# Let's start off by creating an array of 10 evenly spaced elements
x = np.linspace(0,10,num=10, endpoint=False, dtype=int)

# Now lets, reshape the array to the desired shape of 2x5
shape = (2,5)
x_reshaped = np.reshape(x, shape)
print(x)
print(x_reshaped)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


__NOTE:__ that numpy took the last 5 elements of the orginal array, `x`, and created a new row from it.

In [57]:
# Now lets convert back
x_reshaped_reshaped = np.reshape(x_reshaped, (10,))
print(x_reshaped_reshaped)

[0 1 2 3 4 5 6 7 8 9]


We are back to the orinal array

In [58]:
# What happens if we try and "transpose" the reshaped array using reshape?
x_transposed = np.reshape(x_reshaped, (5,2))
print(x_transposed)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Doen't quite work...

## `np.min()` and `np.max()`
the built in Python `min` and `max` are not aware of how to deal with multidimentional arrays. For this we have `np.min()` and `np.max()`

In [37]:
# lets create a new 3x3 array
x = np.arange(1,11).reshape((5,2))
print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [38]:
# Take the min of the matrix
print(np.min(x))

1


In [39]:
# Take the max of the matrix
print(np.max(x))

10


In [40]:
# what if we want the min of each row
print(np.min(x, axis=1))

[1 3 5 7 9]


In [41]:
# like wise the max of each column
print(np.max(x, axis=0))

[ 9 10]


__NOTE:__ that the axis index is reversed to index in shape...

## Accessing elements of Numpy Arrays

We can access element of arrays just as we access elements in a list

In [43]:
# Lets create an array
x = np.arange(1,11)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [44]:
# accessing the first element
print(x[0])

1


In [45]:
# accessing the last element
print(x[-1])

10


In [46]:
# accessing the 2nd through 4th eleents
print(x[1:4])

[2 3 4]


In [49]:
# accessing the all the even indicies
idx = list(range(0,len(x),2))
print(idx)
print(x[idx])

[0, 2, 4, 6, 8]
[1 3 5 7 9]


In [51]:
# accessing all the even values using a booleann mask
mask = (x % 2 == 0)
print(mask)
print(x[mask])

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


## Accessing Elements in a multidimentional array

In [54]:
# Lets create a matrix
matrix = np.arange(0,15).reshape((3,5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [55]:
# Picking out the 2'nd row
matrix[1]

array([5, 6, 7, 8, 9])

In [58]:
# accessing out the  3rd column in the 2nd row
matrix[1][2]

7

In [59]:
# also can do it all in one bracket
matrix[1,2]

7

In [60]:
# Ranges also work
matrix[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
# picking out a subset of the matrix, in this case the first 2x2 matrix
matrix[0:2, 0:2]

array([[0, 1],
       [5, 6]])

In [68]:
# masking works too, but returns
matrix[(matrix > 7)]

array([ 8,  9, 10, 11, 12, 13, 14])

In [69]:
# we can also update values in matrix
matrix[(matrix > 7)] = 100
matrix

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100]])

In [70]:
# what happens when you update a sub matrix?
sub_mat = matrix[0:2, 0:2]
sub_mat[:] = -1
matrix

array([[ -1,  -1,   2,   3,   4],
       [ -1,  -1,   7, 100, 100],
       [100, 100, 100, 100, 100]])

__NOTE:__ Works as expected in python, still reference based

In [71]:
# Lets recreate the orginal matrix
matrix = np.arange(0,15).reshape((3,5))

# Now lets create a sub-matrix, but with copy
sub_mat = matrix[0:2, 0:2].copy()
print(matrix)
print(sub_mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1]
 [5 6]]


In [73]:
# Now let's chage submat and see what happens
sub_mat[:] = -1
print(matrix)
print(sub_mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[-1 -1]
 [-1 -1]]


# Math and Trigonometry with Numpy

## Introduction

Numpy has a number of basic math and triginometric methods included.
full list can be found here:
https://numpy.org/doc/stable/reference/routines.math.html

## Math Methods

### Exponents and Logarithmic

#### `np.exp()`
`np.exp()` takes `e`^`x` for a given `x`. If `x` is an array, `np.exp()` will produce `e^x` for every element within `x`

In [62]:
# Let's create a basic linearly spaced array
x = np.linspace(0,10,num=11)

# lets take the exp of this array
print(x)
print(np.exp(x))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


# Linear Algebra with Numpy

## Introduction
With basic Python, math operations (`+`, `-`, `/`, `*`) on lists does not produce the intended results when compared to a Linear Algebric operation. Numpy solves this problem by vecotorizing these, and other operations so that they are perfomed __element wise__.

For linear algebra functionality built on BLAS and LAPACK - See the following:
https://numpy.org/doc/stable/reference/routines.linalg.html

### Basic Operations (`+`, `-`, `/`, `*`)

In [64]:
# Lets create two arrays (of the same shape)
x = np.linspace(0,10,num=11)
y = np.linspace(1,11,num=11)

print(x)
print(y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [70]:
# lets add them together
print(x)
print(y)
print('-'*50)
print(x + y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------------------------
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


__NOTE:__ that the `+` operation performed and element-wise addition of the arrays `x` and `y`

Likewise subtraction works the same way

In [72]:
print(x)
print(y)
print('-'*50)
print(x - y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------------------------
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


As do `*`, `/` and `**`

In [73]:
print(x)
print(y)
print('-'*50)
print(x * y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------------------------
[  0.   2.   6.  12.  20.  30.  42.  56.  72.  90. 110.]


In [74]:
print(x)
print(y)
print('-'*50)
print(x / y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------------------------
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9        0.90909091]


In [75]:
print(x)
print(y)
print('-'*50)
print(x ** y)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
--------------------------------------------------
[0.00000000e+00 1.00000000e+00 8.00000000e+00 8.10000000e+01
 1.02400000e+03 1.56250000e+04 2.79936000e+05 5.76480100e+06
 1.34217728e+08 3.48678440e+09 1.00000000e+11]


What happens to matricies?

In [9]:
# Lets create two 3x3 matricies and see what happens
x = np.arange(1,10).reshape((3,3))
y = np.ones((3,3))*2
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [10]:
# Addition
print("Addition:")
print(x+y)

# Subtraction
print("Subtraction")
print(x - y)

# Multiplication
print("Multiplication")
print(x*y)

# Division
print("Division")
print(x/y)

# Powers
print("Powers")
print(x**y)

Addition:
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
Subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Division
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
Powers
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


You can see everything operation is performed element-wise

### The `@` Operator

The `@` Oprator takes the dot product of two matricies.

In [14]:
# Lets create a 3x3 matrix
x = np.arange(11,20).reshape((3,3))
# Lets create a 3x3 identity matrix
eye3x3 = np.eye(3)
print(x)
print(eye3x3)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Now lets take the dot product
print(x@eye3x3)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


In [22]:
# Now lets create a 3x1 vector and do the same thing
v = np.array([0,1,0]).reshape((3,1))
print(v)

[[0]
 [1]
 [0]]


In [25]:
print(x@v)

[[12]
 [15]
 [18]]


### `np.transpose()` OR `.T`

Matrix transposion can be accomplished in either of two ways

In [27]:
# Lets create a 2x5 matrix
x = np.arange(1,11).reshape((2,5))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
# Transposition using np.transpose()
print(np.transpose(x))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [29]:
# Tansposition using .T
print(x.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


# Random Sampling

## Introduction
The `np.random` library provides a number of methods to help produce random numbers.

More info can be found here:
https://numpy.org/doc/stable/reference/random/index.html